name: C++ Build and Test

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up MSVC (Visual Studio C++)
      uses: microsoft/setup-msbuild@v1

    - name: Build C++ Project
      run: |
        # Add commands to build your C++ project here
        # For example:
        # g++ -o myprogram.exe mysource.cpp

    - name: Run Tests (if applicable)
      run: |
        # Add commands to run tests if you have them

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact  # Change to a meaningful name
        path: path/to/your/binary/executable  # Replace with the path to your compiled binary
